modLoader="javafml"
loaderVersion="[40,)"
license="MIT"

[[mods]]
modId="cpm_timeline"
version="1.0.0"
displayName="CPM FrameEditor"
description='''
Adds a timeline view for editing CPM animations, similar to Blockbench.
'''

[[dependencies.cpm_timeline]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cpm_timeline]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.cpm_timeline]]
    modId="cpm"
    mandatory=true
    versionRange="[0.6.24,)"
    ordering="AFTER"
    side="CLIENT"
