pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    }
}

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        // Workaround for Loom Gson 2.9.1 reflection crashes on Java 17/21
        classpath 'com.google.code.gson:gson:2.11.0'
    }
}

rootProject.name = 'CPMAnimatorUtilsFabric'
